version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    networks:
      - etswana-network
    volumes:
      - mongodb_data_container:/data/db

  elasticsearch:
    image: elasticsearch:1.7.5
    container_name: elasticsearch
    networks:
       - etswana-network

volumes:
  mongodb_data_container:
networks:
  etswana-network:
    driver: bridge
